# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall

ifeq ($(CONFIG_BORNEO_DTB), y)
EXTRA_CFLAGS += -DCONFIG_AW882XX_CODEC -DCONFIG_AW882XX_DSP
endif

aw882xx_k419-objs = aw882xx.o
obj-$(CONFIG_SND_SOC_AWINIC_AW882XX) += aw882xx_k419.o
